[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
chrono = "0.4.45"
crossterm = "0.29.0"
futures-util = "0.3.34"
protocol = { version = "0.1.0", path = "../protocol" }
ratatui = "0.30.2"
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "time", "sync"] }
tokio-tungstenite = "0.30.0"
unicode-width = "0.2.2"
